CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`legalBusinessName` varchar(255),
	`dba` varchar(255),
	`entityType` varchar(64),
	`federalTaxId` varchar(32),
	`dateEstablished` varchar(16),
	`lengthOfOwnership` varchar(64),
	`typeOfBusiness` varchar(255),
	`businessWebsite` varchar(512),
	`businessPhone` varchar(32),
	`businessEmail` varchar(320),
	`businessAddress` text,
	`mailingAddress` text,
	`amountRequested` varchar(64),
	`useOfFunds` text,
	`urgency` varchar(64),
	`existingAdvances` varchar(16),
	`existingAdvanceDetails` text,
	`ownerFirstName` varchar(128),
	`ownerLastName` varchar(128),
	`ownerTitle` varchar(128),
	`ownershipPercentage` varchar(16),
	`ownerSsn` varchar(16),
	`ownerDob` varchar(16),
	`ownerPhone` varchar(32),
	`ownerEmail` varchar(320),
	`ownerHomeAddress` text,
	`bankName` varchar(255),
	`accountNumber` varchar(64),
	`routingNumber` varchar(32),
	`avgMonthlyRevenue` varchar(64),
	`avgMonthlyDeposits` varchar(64),
	`currentProcessor` varchar(255),
	`monthlyCardVolume` varchar(64),
	`avgTicketSize` varchar(64),
	`chargebackHistory` varchar(255),
	`documents` json,
	`authorizedSignerName` varchar(255),
	`authorizedSignerTitle` varchar(128),
	`consentGiven` varchar(8) DEFAULT 'false',
	`status` enum('new','reviewing','approved','declined','funded') NOT NULL DEFAULT 'new',
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`)
);
